#!/bin/bash

set -e

mysql --protocol=socket --host=localhost -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL

CREATE DATABASE IF NOT EXISTS $MYSQL_TEST_DATABASE;

CREATE USER '$MYSQL_TEST_USER'@'%' IDENTIFIED BY '$MYSQL_TEST_PASSWORD';
GRANT ALL ON $MYSQL_TEST_DATABASE.* TO '$MYSQL_TEST_USER'@'%';

EOSQL